name: Convert SCP Data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout self repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout scp-api data
        uses: actions/checkout@v4
        with:
          repository: scp-data/scp-api
          path: scp-api-data
          ref: main
          fetch-depth: 1 # ⭐ ADD THIS LINE FOR FASTER CLONING ⭐

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 html2text

      - name: Run SCP Conversion Script
        run: |
          python convert_scp.py --source scp-api-data/docs/data/scp/items --output converted_scp_items

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          if git diff --exit-code --quiet converted_scp_items/; then
            echo "No changes detected in converted_scp_items. Skipping commit and push."
          else
            git add converted_scp_items/
            git commit -m "Automated: Update converted SCP items from scp-api"
            git push
            echo "Changes committed and pushed successfully!"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
