name: Export SCPs as GitHub Release

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download SCP API
      run: |
        wget -O scp-api-main.zip https://github.com/scp-data/scp-api/archive/refs/heads/main.zip

    - name: Unzip SCP API
      run: unzip -o scp-api-main.zip

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Convert SCPs to Markdown/Text
      run: node scripts/convert_scp.js

    - name: Zip the output
      run: |
        cd scps
        zip -r ../scp-export.zip .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: "SCP Export $(date +'%Y-%m-%d')"
        tag_name: "export-$(date +'%Y-%m-%d')"
        files: scp-export.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
