name: Export SCPs to Markdown and Text

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # Runs every day at midnight UTC

jobs:
  export_scp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download SCP API main.zip
      run: |
        wget -O scp-api-main.zip https://github.com/scp-data/scp-api/archive/refs/heads/main.zip

    - name: Unzip SCP API
      run: unzip -o scp-api-main.zip

    - name: List unzipped folder for debugging
      run: ls -lR scp-api-main

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run SCP conversion script
      run: node scripts/convert_scp.js

    - name: Commit and push generated SCP files if any
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scps/
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Auto: Update SCP Markdown and text files"
        git push

    - name: Show git status for debugging
      run: git status
